### ISSUE TITLE
information

### ISSUE THREAD

**Issue by HackM3nt3** [ruped24/killchain#1]
Hi buddy, i was looking for some scripts and i saw your repo and i didn't check it very well but i have a question?

is your repo routing metasploit through tor using iptables?

Because that kind of function in a simple script with the other tools would be amazing.

**Comment by ruped24** [comment]
> is your repo routing metasploit through tor using iptables?

Yes.
You can also use the stand-alone [anonymizer](https://github.com/ruped24/toriptables2).
