### ISSUE TITLE
informations about metesploit and tor ip tables

### ISSUE THREAD

**Issue by mdgxxx** [ruped24/killchain#2]
hi buddy, you made a  great tool., in this moment  I'm trying to use it, but i don't have any idea for set up correctly the msfconsole listener, can you help me, I'm student and trying to learn how to use these methods 
thanks a lot,

**Comment by ruped24** [comment]
Hello: mdgxxx
Here is a link to using metasploit with Tor.
https://securityblog.gr/1246/anonymity-first-tor-metasploit/

This is not a support question.  In the future post how to questions on my G+ page.  I will answer them there.
